### ISSUE TITLE
where can i download the yolo models?

### ISSUE THREAD

**Issue by Carryma11** [burningion/poor-mans-deep-learning-camera#1]
I mean where can i download the xxxyolo.cfg and xxxyolo.weights?
help~

**Comment by burningion** [comment]
Hey!

So sorry I didn't get a notification for this.

Not sure if you're still looking, but you can find a link to the proper yolo.cfg and yolo weights at the [Darkflow](https://github.com/thtrieu/darkflow/) repo. 

thtrieu even linked to a Google Drive copy of his models [here](https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU).

You can use the above link. The version I used is `tiny-yolo-voc` for both model and cfg. 

Hope this helps!

**Comment by burningion** [comment]
I added a line to the README, so I'll close this for now. Feel free to reach out and open another issue if you get stuck again. Thanks!
